parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/survey.db'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_sqlite'
        #server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: 'sqlite:///%kernel.project_dir%/var/survey.db'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            #App:
            #    is_bundle: false
            #    type: annotation
            #    dir: '%kernel.project_dir%/src/Entity'
            #    prefix: 'App\Entity'
            #    alias: App
                
            App\Acme\SurveyBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Acme/SurveyBundle/Entity'
                prefix: 'App\Acme\SurveyBundle'
                alias: SurveyBundle
                
            
            App\Acme\AdminBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Acme/AdminBundle/Entity'
                prefix: 'App\Acme\AdminBundle'
                alias: AdminBundle