index:
    path: /
    controller: App\Acme\SurveyBundle\Controller\SurveyController::index

admin:
    path: admin/
    controller: App\Acme\AdminBundle\Controller\AdminController::index

App\Acme\SurveyBundle\Controller\:
    resource: '@SurveyBundle/Controller'
    type: annotation
        
App\Acme\AdminBundle\Controller\:
    resource: '@AdminBundle/Controller'
    type: annotation